add_newline = false
format = "$username$hostname $directory$git_branch$git_state$git_status$status$character"

[username]
show_always = true
format = "[$user]($style)@"
style_user = "green"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "blue"

[directory]
format = "[$path]($style)"
style = "green"
fish_style_pwd_dir_length = 1
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
symbol = ""
format = " ([\\($branch\\)]($style))"
style = "purple"

[git_state]
format = " ([$state( $progress_current/$progress_total)]($style))"
style = "yellow"

[git_status]
format = "( [$all_status$ahead_behind]($style))"
style = "red"
conflicted = "!"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
untracked = "?"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕${ahead_count}⇣${behind_count}"

[status]
format = " [\\[$status\\]]($style)"
style = "red"
pipestatus = true
map_symbol = false
recognize_signal_code = true
disabled = false

[character]
format = "> "
